services:
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:RELEASE.2025-02-21T16-00-46Z
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb -p local/dvc || true;
      mc anonymous set none local/dvc || true;
      exit 0;"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    container_name: mlflow
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install --no-cache-dir psycopg2-binary==2.9.9 &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
      --default-artifact-root /mlflow_artifacts"
    volumes:
      - mlflow_artifacts:/mlflow_artifacts

  zenml-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: zenml-server
    ports:
      - "8237:8237"
    volumes:
      - .:/workspace
      - zenml_data:/root/.config/zenml
    working_dir: /workspace
    command: bash -lc "zenml login --local --blocking --ip-address 0.0.0.0 --port 8237"

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    depends_on:
      - mlflow
      - minio
      - minio-init
      - zenml-server
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      ZENML_SERVER_URL: http://zenml-server:8237
      SIMULATE_DRIFT: "0"
      MINIO_ENDPOINT_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: dvc
      MINIO_DATA_PREFIX: datasets/cifar10/raw
    volumes:
      - .:/workspace
      - mlflow_artifacts:/mlflow_artifacts
      - zenml_data:/root/.config/zenml
    working_dir: /workspace
    command: bash -lc "sleep infinity"

volumes:
  minio_data:
  pg_data:
  mlflow_artifacts:
  zenml_data: